services:
    # Factory
    whatwedo_table.factory.table:
        class: whatwedo\TableBundle\Factory\TableFactory
        arguments:
            - '@event_dispatcher'
            - '@request_stack'
            - '@templating'
            - '@whatwedo_table.repository.filter'

    # Events
    whatwedo_table.event_listener.order:
        class: whatwedo\TableBundle\EventListener\OrderEventListener
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: orderResultSet, priority: 100 }

    whatwedo_table.event_listener.filter:
        class: whatwedo\TableBundle\EventListener\FilterEventListener
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: filterResultSet, priority: 100 }

    whatwedo_table.event_listener.search:
        class: whatwedo\TableBundle\EventListener\SearchEventListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: whatwedo_table.data_load.pre_load, method: searchResultSet, priority: 100 }

    whatwedo_ajax.event_listener.search:
      class: whatwedo\TableBundle\EventListener\AjaxFilterSearchListener
      arguments:
            - "@doctrine.orm.entity_manager"
            - "@service_container"
      tags:
            - { name: kernel.event_listener, event: whatwedo_ajax.result_request.filter_set, method: searchResultSet, priority: 100 }
            - { name: kernel.event_listener, event: whatwedo_ajax.result_request.relation_set, method: searchResultSet, priority: 100 }

    # Twig Extension
    sybio.twig_extension:
        class: whatwedo\TableBundle\Twig\TableExtension
        arguments:
            - "@service_container"
        public: false
        tags:
            - { name: twig.extension, priority: 255 }

    # Repository
    whatwedo_table.repository.filter:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - whatwedo\TableBundle\Entity\Filter
